vich_uploader:
    db_driver: orm

    mappings:
        user_gallery:
            uri_prefix: /images/user_gallery
            upload_destination: '%kernel.project_dir%/public/images/user_gallery'
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y/m' # will create directory "2019/05/"
                    date_time_property: uploadTimestamp # see above example
            namer:
                service: Vich\UploaderBundle\Naming\Base64Namer
            inject_on_load: false #default value
            delete_on_update: true #default value
            delete_on_remove: true #default value
